<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Note_create_new_recipeList</name>
   <tag></tag>
   <elementGuidId>38c53c06-d964-4fd3-990c-b279b2c6bbee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='create_new_recipeList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#create_new_recipeList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Create New Recipe List&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2d925259-8091-4ca0-980d-f578c44a6281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative after:absolute after:left-0 after:bottom-[4px] after:w-full after:h-[1px] after:bg-brandSecondary</value>
      <webElementGuid>6f3d3fa3-702d-48cd-b2fa-4228e96391da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create_new_recipeList</value>
      <webElementGuid>afeed6dd-3de4-4fc2-8321-0ae51e4ca261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create New Recipe List</value>
      <webElementGuid>5bcf2203-bd50-4803-b6a9-4a80d1bb599a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create_new_recipeList&quot;)</value>
      <webElementGuid>61596bd3-c141-4022-90bf-52ad32c98385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='create_new_recipeList']</value>
      <webElementGuid>1e3ff17f-1e19-4702-873b-9c5c6fcbeb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='start-of-content']/div/div[3]/div/div/div/button/span[2]</value>
      <webElementGuid>4342173c-3896-410b-b61b-cda9e9672b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note:'])[1]/following::span[2]</value>
      <webElementGuid>d4fce65b-ba6b-4393-8bc2-7ef3e7863b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Recipe Lists'])[2]/following::span[2]</value>
      <webElementGuid>f47724df-df0f-48a9-8d5c-ef57b7a49902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::span[1]</value>
      <webElementGuid>9d7da1bd-7196-4928-8687-a48bd30b2384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge'])[1]/preceding::span[2]</value>
      <webElementGuid>44d9ef61-4c04-4915-8902-714894e24ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create New Recipe List']/parent::*</value>
      <webElementGuid>aa02444c-ef0d-4593-b32e-87392cc32953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button/span[2]</value>
      <webElementGuid>07edd7f7-446f-4f16-9816-993542e25b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'create_new_recipeList' and (text() = 'Create New Recipe List' or . = 'Create New Recipe List')]</value>
      <webElementGuid>7bd8fee5-f75a-45ec-b343-d1f596f68dc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
