<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name your shopping list_createListInput</name>
   <tag></tag>
   <elementGuidId>bd7833dd-8497-4e6f-ad99-96e72370e66a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createListInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createListInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g Sunday BBQ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffc6edf9-4fff-4a7c-b86f-32d188524b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-solid border-[1px] p-4 w-full h-14 border-grey350 rounded py-1 placeholder:text-brandBlack focus-visible:outline-brandBlack</value>
      <webElementGuid>32cc8138-5798-44fd-becd-0c3dbaf9ad91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createListInput</value>
      <webElementGuid>a7070105-fce3-4546-829a-89e86f0c1785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g Sunday BBQ</value>
      <webElementGuid>8587fc9d-5986-480c-aca5-85dde09327fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>3173dd70-bff6-4717-8ab0-60178f027d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>548c2497-a171-4a24-a4c4-eea300b8b283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43737af8-bbe0-45ef-af05-4958480c8888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>createListInput</value>
      <webElementGuid>e8b51f2a-8274-48f3-ae46-9e740838ec75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createListInput&quot;)</value>
      <webElementGuid>a8b44efc-3c74-4b8b-bc45-1e8d27b22662</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createListInput']</value>
      <webElementGuid>5f062037-f79a-48b6-96c4-a92f67aee07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>e023abdd-2c02-4a30-a676-2facadbcf379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'createListInput' and @placeholder = 'e.g Sunday BBQ' and @type = 'text' and @name = 'createListInput']</value>
      <webElementGuid>3bc41d5b-77c2-4978-aa67-1d12691f1ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
