<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add to Meal Plan_flex justify-end item_bb69e1</name>
   <tag></tag>
   <elementGuidId>7366f619-621e-4570-a1be-f88ca8ccfc63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='recipe_favorite_0']/span/div/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.text-\[18px\] > .flex >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>019527e3-2a40-40ca-b4f4-f10de5c97aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex justify-end items-center rounded-full bg-brandWhite p-[10px] icon-add-calender text-brandSecondary transition-all duration-500 z-20</value>
      <webElementGuid>9d85d325-38d2-41f8-8ee2-30095bb5f5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-of-content&quot;)/div[1]/div[@class=&quot;mx-auto px-6 2md:px-12 max-w-[1536px] main-wrapper lg:mt-6&quot;]/div[@class=&quot;flex lg:gap-[24px]&quot;]/main[@class=&quot;pb-8 md:pb-6 lg:pb-12 w-full lg:w-[calc(100%-250px)] xl:w-[calc(100%-220px)]&quot;]/div[@class=&quot;grid-outer&quot;]/div[@class=&quot;pb-6 [&amp;_.recipeSecton>:first-child]:pr-0 [&amp;_.recipeSecton>:last-child]:mr-[-24px] 2md:[&amp;_.recipeSecton>:last-child]:mr-[-48px] lg:[&amp;_.recipeSecton>:last-child]:mr-0&quot;]/div[@class=&quot;bg-brandWhite&quot;]/div[1]/div[@class=&quot;grid xl:grid-cols-2 md:gap-[16px] lg:gap-[24px] gap-[24px] recipeSecton&quot;]/div[@class=&quot;p-[1px] flex flex-row gap-2 md:gap-6 items-stretch h-full overflow-x-auto lg:overflow-visible lg:grid lg:grid-cols-2 2lg:grid-cols-4 xl:grid-cols-2 scrollbar-hide whitespace-nowrap pr-6 lg:pr-0 homerecipe&quot;]/div[@class=&quot;relative pb-10 bg-brandWhite shadow-[0px_0px_2px_0px_rgba(0,0,0,0.25)] rounded-lg overflow-hidden block h-full min-w-[260px] md:min-w-[285px] lg:min-w-[unset]&quot;]/div[@class=&quot;bg-brandWhite rounded-lg overflow-hidden shadow-none&quot;]/div[@class=&quot;relative bg-grey300 min-h-[150px] overflow-hidden&quot;]/div[@class=&quot;absolute bottom-[60px] right-[19px] flex gap-2 flex-col&quot;]/div[@id=&quot;recipe_favorite_0&quot;]/span[@class=&quot;tab rounded-full cursor-pointer bg-brandWhite [&amp;>span]:text-brandSecondary&quot;]/div[@class=&quot;relative overflow-hidden&quot;]/span[@class=&quot;text-[18px] h-[40px] w-[40px] group flex justify-end items-center text-brandBlack rounded-full border border-brandSecondary relative transition-all duration-500 hover:border-brandSecondary z-[9] hover:w-[172px]&quot;]/span[@class=&quot;flex justify-end items-center rounded-full bg-brandWhite p-[10px] icon-add-calender text-brandSecondary transition-all duration-500 z-20&quot;]</value>
      <webElementGuid>3b753c00-cbb3-4574-bf3e-e4a6e729d19f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recipe_favorite_0']/span/div/span/span[2]</value>
      <webElementGuid>a65a1035-d204-4777-a26c-7c52820e2639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/span/span[2]</value>
      <webElementGuid>82310811-e320-4820-835e-10282941d714</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
