<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sort_border-d6d6d6  w-full text-left_251865_1</name>
   <tag></tag>
   <elementGuidId>8445a8cf-ee85-448d-995f-139552e813c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;Sort articles&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c54b67e6-cc1f-484b-a7e3-f3018e78c114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f9afc541-5f02-40a7-85b6-adbad02e1cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>1584626e-24aa-43dc-9da4-a2e0a6122ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6a2ab00b-a4eb-4b1a-b08e-95ef0ae3e065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>91632f94-05cf-4004-ba84-db39fa418d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sort articles</value>
      <webElementGuid>a6b48937-cc55-4660-943d-9ce36daab41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49eb6fe7-1d61-487e-b4ac-15edd42ca377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-[#d6d6d6]  w-full text-left border rounded-[4px] pt-[15px] pb-[12px] pl-[20px] pr-[40px] text-brandBlack text-[14px] leading-normal relative</value>
      <webElementGuid>94ef5c64-1999-4b99-b26c-f204ebf9144d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alphabetical: A-Z</value>
      <webElementGuid>451dde92-b872-4531-99b5-67f255d2b8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_00123d __className_a398cb __className_d7edc2 __variable_d7edc2 __variable_7b4501 site-safeway&quot;]/div[3]/div[1]/div[1]/div[@class=&quot;h-full min-h-[400px] visible&quot;]/div[2]/div[@class=&quot;mx-auto 2md:px-12 max-w-[1536px] w-full px-0 lg:px-12&quot;]/div[@class=&quot;row  !mx-0&quot;]/div[@class=&quot;col-12 !px-0&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;aria-selected:block hidden [&amp;_.main-wrapper]:!px-0 [&amp;_.main-wrapper] [&amp;_.main-wrapper_.filter-mobile]:!bg-grey100 [&amp;_.main-wrapper_.filter-mobile]:lg:before:content-none [&amp;_.main-wrapper_.filter-mobile]:lg:before:content-none [&amp;_.main-wrapper_.filter-mobile]:before:content-[''] [&amp;_.main-wrapper_.filter-mobile]:before:absolute [&amp;_.main-wrapper_.filter-mobile]:before:left-[-64px] [&amp;_.main-wrapper_.filter-mobile]:before:top-0 [&amp;_.main-wrapper_.filter-mobile]:before:w-[24%] [&amp;_.main-wrapper_.filter-mobile]:before:h-full [&amp;_.main-wrapper_.filter-mobile]:relative [&amp;_.main-wrapper_.filter-mobile]:before:bg-grey100 [&amp;_.main-wrapper_.filter-mobile]:after:content-[''] [&amp;_.main-wrapper_.filter-mobile]:after:absolute [&amp;_.main-wrapper_.filter-mobile]:2md:after:right-[-48px] [&amp;_.main-wrapper_.filter-mobile]:after:right-0 [&amp;_.main-wrapper_.productMain_.filter-mobile]:after:right-[-24px] [&amp;_.main-wrapper_.filter-mobile]:after:top-0 [&amp;_.main-wrapper_.filter-mobile]:2md:after:w-[calc(100%-48px)] [&amp;_.main-wrapper_.filter-mobile]:after:w-[calc(100%-24px)] [&amp;_.main-wrapper_.productMain_.filter-mobile]:2md:after:right-[-48px] [&amp;_.main-wrapper_.productMain_.filter-mobile]:px-0 [&amp;_.main-wrapper_.productMain_.filter-mobile>div]:md:w-auto [&amp;_.main-wrapper_.filter-mobile]:after:h-full [&amp;_.main-wrapper_.filter-mobile]:relative [&amp;_.main-wrapper_.filter-mobile]:after:bg-grey100 [&amp;_.main-wrapper_.filter-mobile]:bg-grey350[&amp;_.main-wrapper_.filter-mobile]:2md:bg-brandWhite [&amp;_.main-wrapper_.filter-mobile]:py-[16px] [&amp;_.main-wrapper_.filter-mobile]:px-6 [&amp;_.main-wrapper_.filter-mobile]:2md:px-0 [&amp;_.main-wrapper_.recipeMain]:px-6 [&amp;_.main-wrapper_.recipeMain]:2md:px-0 [&amp;_.main-wrapper_.row]:!m-0 [&amp;_.main-wrapper_.col-12]:!px-0 [&amp;_.productWrapper]:!px-0 [&amp;_.main-wrapper_.productMain]:pt-0 [&amp;_.main-wrapper_.productMain]:2md:px-0 [&amp;_.main-wrapper_.productMain]:px-6 [&amp;_.main-wrapper_.articleMain]:px-6 [&amp;_.main-wrapper_.articleMain]:2md:px-0  [&amp;_.main-wrapper_.grid-outer]:pt-0 [&amp;_.main-wrapper_.products-p]:px-6 [&amp;_.main-wrapper_.products-p]:2md:px-0 [&amp;_.main-wrapper_.products-p]:m-0&quot;]/div[1]/div[@class=&quot;mx-auto px-6 2md:px-12 max-w-[1536px] main-wrapper lg:mt-6&quot;]/div[@class=&quot;flex lg:gap-[24px]&quot;]/aside[@class=&quot;lg:w-[250px] xl:w-[220px] mb-[38px] sideBar&quot;]/div[@class=&quot;flex flex-col gap-4 lg:w-[250px] xl:w-[220px]&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@id=&quot;recipe_tour_1&quot;]/div[@class=&quot;relative [&amp;>button]:text-grey900 [&amp;>button]:rounded-[4px] [&amp;>button]:pl-4 [&amp;>button]:h-[56px] [&amp;>button]:py-3 [&amp;>button]:pr-12 [&amp;>button>span]:text-base [&amp;>ul]:!shadow-[0_4px_30px_0px_rgba(0,0,0,0.2)]&quot;]/button[@class=&quot;border-[#d6d6d6]  w-full text-left border rounded-[4px] pt-[15px] pb-[12px] pl-[20px] pr-[40px] text-brandBlack text-[14px] leading-normal relative&quot;]</value>
      <webElementGuid>02a914b2-3a41-49f1-b7b0-86253e516156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>e05ff270-f223-4386-92fa-f9a0ec06a3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='recipe_tour_1']/div/button)[3]</value>
      <webElementGuid>fa170d92-4787-494c-80fc-f791440b4cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[3]/following::button[1]</value>
      <webElementGuid>a515fc03-6df6-4103-878f-51b3c43fb26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page Main Heading'])[3]/following::button[1]</value>
      <webElementGuid>cdf71f53-7c9c-4cfc-899c-9505cb740983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[6]/preceding::button[1]</value>
      <webElementGuid>79e780ea-3f98-4c26-8fae-20046537e555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/aside/div/div/div[2]/div/button</value>
      <webElementGuid>05d82d81-6535-4621-9991-9e0037f600e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Alphabetical: A-Z' or . = 'Alphabetical: A-Z')]</value>
      <webElementGuid>5fa83662-d05f-43ef-af67-39c15f57a08b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
