<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete_items-center justify-center t_811c2c</name>
   <tag></tag>
   <elementGuidId>bceea62c-7932-4fdc-a5a9-6967f6bc934b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='start-of-content']/div/div/div/div/div[2]/div/div/div/div/div[2]/div/ul/li[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Print&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>672b94e1-887e-4d3f-b6cf-6212f83de6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>items-center justify-center transition relative overflow-hidden z-[1] border-[1px] cursor-pointer before:content-[''] before:absolute before:inset-0 before:w-[150%] before:h-full before:transform before:translate-x-[-120%] before:skew-x-[-35deg] before:origin-[0_0] before:transition-transform before:duration-[1s] before:ease-[cubic-bezier(0.07,0.51,0.12,1)] before:z-[-1] hover:before:translate-x-0 focus:before:translate-x-0 border-none py-4 px-3 block text-brandBlack w-full hover:bg-grey300 text-left rounded-none font-normal</value>
      <webElementGuid>684dd8e8-a0b6-41b5-bbcf-28a23c5ab51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Print</value>
      <webElementGuid>8395daef-3309-43d9-9789-e34253a4c68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>47d7a700-6b51-49c1-a35b-e6e313b19d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-of-content&quot;)/div[1]/div[@class=&quot;max-w-[1424px] mx-auto px-6 2md:px-12 !max-w-[1536px]&quot;]/div[@class=&quot;row my-6&quot;]/div[@class=&quot;col-12 col-xl-12&quot;]/div[@class=&quot;min-h-[510px]&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-xs-6 col-lg-3 mb-6&quot;]/div[@class=&quot;bg-brandWhite rounded-lg shadow-[0_0_4px_0_rgba(0,0,0,0.25)] !rounded-large overflow-visible h-full relative&quot;]/div[@class=&quot;p-4 border-b flex items-center justify-center !pb-0 !border-[0px] !pt-2 !px-4 relative h-[141px] sm:h-[254px] lg:h-[238px]&quot;]/div[@class=&quot;relative inline-block !absolute !right-[16px] md:!right-[20px] !top-[16px] !text-center z-[2]&quot;]/div[@class=&quot;mt-2 p-3 rounded-lg z-[999] transform transition-all duration-300 ease-in-out opacity-100 scale-100 w-[200px] min-w-[200px] absolute -right-[4px] left-auto bottom-auto !text-left py-2 px-0 shadow-[0_0_4px_0_rgba(0,0,0,0.25)] !rounded-large bg-brandWhite&quot;]/ul[1]/li[3]/button[@class=&quot;items-center justify-center transition relative overflow-hidden z-[1] border-[1px] cursor-pointer before:content-[''] before:absolute before:inset-0 before:w-[150%] before:h-full before:transform before:translate-x-[-120%] before:skew-x-[-35deg] before:origin-[0_0] before:transition-transform before:duration-[1s] before:ease-[cubic-bezier(0.07,0.51,0.12,1)] before:z-[-1] hover:before:translate-x-0 focus:before:translate-x-0 border-none py-4 px-3 block text-brandBlack w-full hover:bg-grey300 text-left rounded-none font-normal&quot;]</value>
      <webElementGuid>1797bbfd-c156-46fc-9a30-b20402fbdb48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='start-of-content']/div/div/div/div/div[2]/div/div/div/div/div[2]/div/ul/li[3]/button</value>
      <webElementGuid>5335c9e5-0529-456a-85a9-c24405c6d9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::button[1]</value>
      <webElementGuid>edaac3ea-3fc0-4f03-a5c9-ada8c19ac1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rename'])[1]/following::button[2]</value>
      <webElementGuid>ae301291-a072-4504-b69a-eff4ea6bd31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[5]/preceding::button[1]</value>
      <webElementGuid>cb14f763-37bd-445f-8d6e-4ede6f056cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Service'])[1]/preceding::button[1]</value>
      <webElementGuid>9ff8a964-1155-46fa-9540-d8cfa1f9120e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>18e51cc1-b972-4bb8-a909-65bdeadf85af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button</value>
      <webElementGuid>6bd31d28-dc25-4db7-bacc-ef149859c20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>ef98221e-3abe-4ae3-9c83-c095739b0c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[5]/preceding::button[1]</value>
      <webElementGuid>be0545c5-3102-4229-896e-879aa30fea52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
