<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add New List_items-center justify-ce_03fb78</name>
   <tag></tag>
   <elementGuidId>f749f87c-ea41-4578-a0c4-a38de8414ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='start-of-content']/div/div/div/div/div[2]/div/div/div/div/div[2]/div/ul/li/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rename&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c62204c-8200-4de2-985a-c3989ff9f4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>items-center justify-center transition relative overflow-hidden z-[1] border-[1px] cursor-pointer before:content-[''] before:absolute before:inset-0 before:w-[150%] before:h-full before:transform before:translate-x-[-120%] before:skew-x-[-35deg] before:origin-[0_0] before:transition-transform before:duration-[1s] before:ease-[cubic-bezier(0.07,0.51,0.12,1)] before:z-[-1] hover:before:translate-x-0 focus:before:translate-x-0 border-none py-4 px-3 block text-brandBlack w-full hover:bg-grey300 text-left rounded-none font-normal</value>
      <webElementGuid>4cb9ad94-e414-4a70-863f-9fb00314c5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rename</value>
      <webElementGuid>6c0e0138-5de8-4389-a4b3-3630224afa66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rename</value>
      <webElementGuid>94ca9ee3-3ab9-45e5-bb19-33bb316088ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-of-content&quot;)/div[1]/div[@class=&quot;max-w-[1424px] mx-auto px-6 2md:px-12 !max-w-[1536px]&quot;]/div[@class=&quot;row my-6&quot;]/div[@class=&quot;col-12 col-xl-12&quot;]/div[@class=&quot;min-h-[510px]&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-xs-6 col-lg-3 mb-6&quot;]/div[@class=&quot;bg-brandWhite rounded-lg shadow-[0_0_4px_0_rgba(0,0,0,0.25)] !rounded-large overflow-visible h-full relative&quot;]/div[@class=&quot;p-4 border-b flex items-center justify-center !pb-0 !border-[0px] !pt-2 !px-4 relative h-[141px] sm:h-[254px] lg:h-[238px]&quot;]/div[@class=&quot;relative inline-block !absolute !right-[16px] md:!right-[20px] !top-[16px] !text-center z-[2]&quot;]/div[@class=&quot;mt-2 p-3 rounded-lg z-[999] transform transition-all duration-300 ease-in-out opacity-100 scale-100 w-[200px] min-w-[200px] absolute -right-[4px] left-auto bottom-auto !text-left py-2 px-0 shadow-[0_0_4px_0_rgba(0,0,0,0.25)] !rounded-large bg-brandWhite&quot;]/ul[1]/li[1]/button[@class=&quot;items-center justify-center transition relative overflow-hidden z-[1] border-[1px] cursor-pointer before:content-[''] before:absolute before:inset-0 before:w-[150%] before:h-full before:transform before:translate-x-[-120%] before:skew-x-[-35deg] before:origin-[0_0] before:transition-transform before:duration-[1s] before:ease-[cubic-bezier(0.07,0.51,0.12,1)] before:z-[-1] hover:before:translate-x-0 focus:before:translate-x-0 border-none py-4 px-3 block text-brandBlack w-full hover:bg-grey300 text-left rounded-none font-normal&quot;]</value>
      <webElementGuid>53ddef4d-ffbf-4520-b9a4-4fe8e3a02bf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='start-of-content']/div/div/div/div/div[2]/div/div/div/div/div[2]/div/ul/li/button</value>
      <webElementGuid>43c3c306-e0e4-4294-9dd1-42b31ae5f1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New List'])[1]/following::button[2]</value>
      <webElementGuid>80adef0e-f9ea-4611-aaf1-781215fd6578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage List'])[1]/following::button[3]</value>
      <webElementGuid>4096150f-fd72-4613-b074-db6b8f0b402f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::button[1]</value>
      <webElementGuid>17f2b910-ed18-4cc5-bed9-737f8b1878a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/preceding::button[2]</value>
      <webElementGuid>f5ac4136-6dbc-4f1d-a837-625e4a8e3778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rename']/parent::*</value>
      <webElementGuid>56aed71f-01a8-43af-b925-e32986d6ca56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>d42e4844-f208-4472-84af-6e0e18622c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Rename' or . = 'Rename')]</value>
      <webElementGuid>5dba7152-ff5b-4152-b2e9-f9c3c837595d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
