<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rename this shopping list_renameListInput</name>
   <tag></tag>
   <elementGuidId>b1c3373c-0c22-453e-8a62-dc895afd4769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#renameListInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='renameListInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your list name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a24643dc-a42a-4372-90a5-b9b4773ad206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-solid border-[1px] p-4 w-full h-14 border-grey350 rounded py-1 placeholder:text-brandBlack focus-visible:outline-brandBlack</value>
      <webElementGuid>77e4da8d-187d-4ec0-8613-a2636f5b0c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renameListInput</value>
      <webElementGuid>467b44b8-d161-4526-9e77-c407840e8d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your list name</value>
      <webElementGuid>f8e1ab47-5134-447e-8e0c-0a975a161451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c0c55e6-a841-45bd-aafd-74f75d4fb07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>762e77b2-1ec5-4094-b33a-a4c23428ccf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>renameListInput</value>
      <webElementGuid>177d3d9e-bda3-4847-90f4-ca7583fef6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;renameListInput&quot;)</value>
      <webElementGuid>f1c6d4fe-64fd-4903-9734-650a94f12e31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='renameListInput']</value>
      <webElementGuid>6cdb786d-ec5b-4e3e-b32a-6b7a954e81ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/input</value>
      <webElementGuid>0b247a97-91c2-4df6-9674-ddd6019a626d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'renameListInput' and @placeholder = 'Enter your list name' and @type = 'text' and @name = 'renameListInput']</value>
      <webElementGuid>ec21fbbe-a732-4216-b280-42cbabc5a1cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
