<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>List creation field</name>
   <tag></tag>
   <elementGuidId>f99bd63c-f05a-4443-b229-9e01c20ba8df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createListInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createListInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g Sunday BBQ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a9b0c70-65e3-43dd-b690-eef8f944c641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-solid border-[1px] p-4 w-full h-14 border-grey350 rounded py-1 placeholder:text-brandBlack focus-visible:outline-brandBlack</value>
      <webElementGuid>076c85e9-bb58-49b2-997c-fca573f08099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createListInput</value>
      <webElementGuid>50a3fd55-99e5-4e50-80a9-a7995e3463ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g Sunday BBQ</value>
      <webElementGuid>5109382c-e43b-4a46-ae8a-2bd91cba2783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>1aea540d-08fb-4ec9-87d5-2c699bf27c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c853c43c-694a-4fdd-a8ae-21fe94b8ad6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cfc05391-ce52-4e6a-8166-7c9afe2b157c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>createListInput</value>
      <webElementGuid>ea6bbfd2-d661-419d-8cb4-4ea24f5e3164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createListInput&quot;)</value>
      <webElementGuid>fbeb0428-3498-4fd0-93ab-ccc50ebf2224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createListInput']</value>
      <webElementGuid>09721e3c-ebf4-4d88-8e89-4aeaf5e368f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>b3b6ab57-a609-4d28-8fa8-6dbb6cabcb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'createListInput' and @placeholder = 'e.g Sunday BBQ' and @type = 'text' and @name = 'createListInput']</value>
      <webElementGuid>d896888a-e0e1-42c9-8607-4a3d4cce3429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
