<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__gigya-textbox-48351557999388700</name>
   <tag></tag>
   <elementGuidId>be6ba428-7cf9-4574-85ef-bc82e557de89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-textbox-48351557999388700</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-textbox-48351557999388700']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Insert last name *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1c92666-bc16-4a4e-9eeb-a729efaa9c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>5328d331-8389-49e2-99b5-323c028e65a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54d772ca-e538-4a07-8dc5-448def5336d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-text</value>
      <webElementGuid>09f381fb-8d2a-448b-ba75-ea2d1322412c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be1755ef-747b-4db3-9d09-f4b5d88ecfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile.lastName</value>
      <webElementGuid>1c01023b-0ebd-492a-9c97-f55a3cb6b8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-display-name</name>
      <type>Main</type>
      <value>screenset.translations['TEXTBOX_55501138512271200_DISPLAY_NAME']</value>
      <webElementGuid>1ed2aeee-f0d7-4597-b181-3f33f73b62f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-gigya-placeholder</name>
      <type>Main</type>
      <value>screenset.translations['TEXTBOX_55501138512271200_PLACEHOLDER']</value>
      <webElementGuid>08f12fd0-f051-4f4d-a944-598c0bb018a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-textbox-48351557999388700</value>
      <webElementGuid>4fd67df0-b806-479b-8a0d-16c6e49eec40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba9ce719-9c8a-4b0c-82e9-940084dbf97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>e00a4e74-9ac3-4332-bb86-56f89a5a2735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>profile.lastName</value>
      <webElementGuid>9215572b-8bf9-43c2-9920-28445ed55b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-textbox-48351557999388700</value>
      <webElementGuid>779de5bc-0087-4226-b401-4dfaeeb2fa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d2fc07e0-c09f-4d14-a6fe-d18eec4abec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-display-name</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>99cef104-a4f9-42f7-95e7-5960d40d3950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-placeholder</name>
      <type>Main</type>
      <value>Insert last name</value>
      <webElementGuid>59124a13-38b2-4aff-a1f5-1f73490f44bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert last name *</value>
      <webElementGuid>07a3366c-5542-4613-8bc2-c03aef022af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-textbox-48351557999388700&quot;)</value>
      <webElementGuid>61d88c41-c09a-4981-8aa4-a25e89ee54a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-textbox-48351557999388700']</value>
      <webElementGuid>1aa4c794-b89e-4044-b02d-a8824e90679b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>335131fe-ac38-4a5b-bad8-66f912e82ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>36bd0936-9e1b-4666-938e-98a94f5eb033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Last name' and @type = 'text' and @name = 'profile.lastName' and @id = 'gigya-textbox-48351557999388700' and @placeholder = 'Insert last name *']</value>
      <webElementGuid>e35e4102-1dcc-42df-a569-50a0af64ac93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
