<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Privacy Policy_gigya-input-submit lef_838139</name>
   <tag></tag>
   <elementGuidId>fabacc0b-3888-4b4a-9c60-9a26c92a4322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-subscribe-with-email-form > div.gigya-layout-row > div.gigya-layout-row > div.gigya-composite-control.gigya-composite-control-submit > input.gigya-input-submit.left-aligned</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Submit&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04aec3e2-e360-4e90-8b7a-f7e0f6bee696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12e162c3-1c49-4d24-ac39-ae78b4bcd9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-submit left-aligned</value>
      <webElementGuid>afaf2dae-8423-435c-b33a-38e37e0ed07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6c28ada8-8f9e-4cb3-b20f-0cf71a75614d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c0a0bb4a-f25e-4b8f-b4cb-7b1058057b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:value</name>
      <type>Main</type>
      <value>screenset.translations['SUBMIT_8528365233759930_VALUE']</value>
      <webElementGuid>614b1b5a-7092-416b-ac23-1dbf17f55236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_7_1757078243999</value>
      <webElementGuid>2e8dc06b-2126-4f24-a768-0ef944ef459d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a37b3024-aca1-4734-8069-feb27a1c39cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>7bcdd409-4d5c-4d7a-8f26-6f85479cc8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>b49048e2-9c2d-4289-ab3c-8b4d1c3dcebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-subscribe-with-email-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-submit&quot;]/input[@class=&quot;gigya-input-submit left-aligned&quot;]</value>
      <webElementGuid>f5c7a790-878e-4b3b-8cb9-5ab60dd87f15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Submit']</value>
      <webElementGuid>807df8c6-a3b1-474e-86f9-06504aba24ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[7]/div[4]/input</value>
      <webElementGuid>fca96b1d-7693-4e29-bdce-f325f981cd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[7]/div[4]/input</value>
      <webElementGuid>9ee9a17b-9d8e-4836-a7bd-cf74b808a0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>e7e52dfb-b019-47c9-aa02-eafb85a2faa9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
