<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__gigya-textbox-99294980864804060</name>
   <tag></tag>
   <elementGuidId>f8cf0d38-eb6c-470d-97bd-b95e9fe15dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-textbox-99294980864804060</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gigya-textbox-99294980864804060']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Insert postal code *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74c0f6fd-fee8-4359-ac4f-c70cee88cb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Postal code</value>
      <webElementGuid>43db054b-e988-498a-aca3-d04759403562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data.postalCode</value>
      <webElementGuid>b70422ff-e98b-42dc-a611-5d23adc04420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-input-text copyTextField</value>
      <webElementGuid>782918b0-02b0-40d5-ab37-b8e720dd9239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5435fcb-560a-4301-baa3-a758900e4c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89b479fe-ba0a-4b83-9f9d-de6ab2d69c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-display-name</name>
      <type>Main</type>
      <value>screenset.translations['TEXTBOX_150139197864903580_DISPLAY_NAME']</value>
      <webElementGuid>175b945a-cac2-4b1f-85b2-caeaa49b3afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gigya-expression:data-gigya-placeholder</name>
      <type>Main</type>
      <value>screenset.translations['TEXTBOX_150139197864903580_PLACEHOLDER']</value>
      <webElementGuid>70cd15dc-f3c8-44ee-88fd-31edeef40021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>gigya-textbox-99294980864804060</value>
      <webElementGuid>ff86d563-4ec8-4e20-9390-e34aa9c78765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9db24b26-4b79-4033-aece-c438e9d0dd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>001484b8-1350-4b32-86b3-b1004de30d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-name</name>
      <type>Main</type>
      <value>data.postalCode</value>
      <webElementGuid>9822a50c-5d62-4427-9710-97af1fa652bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-textbox-99294980864804060</value>
      <webElementGuid>bef07c45-cece-46bb-ae07-c265765aa593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2544e123-8734-4c0a-a2a7-d74de114ad17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-display-name</name>
      <type>Main</type>
      <value>Postal code</value>
      <webElementGuid>500e9ce2-4ef1-4d2e-8d1e-d4df946c3ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gigya-placeholder</name>
      <type>Main</type>
      <value>Insert postal code</value>
      <webElementGuid>1243753c-ddd6-4380-bf00-b22b1228c873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert postal code *</value>
      <webElementGuid>2df8507b-9451-45d4-b5cd-742d79d6a699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-textbox-99294980864804060&quot;)</value>
      <webElementGuid>ae4058bc-307f-4730-93c8-ea027ead004d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gigya-textbox-99294980864804060']</value>
      <webElementGuid>2d528809-389d-4c21-9a5b-3c37ab82a1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[4]/div/input</value>
      <webElementGuid>e887882b-43c9-4977-96fa-8998c9c26da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[4]/div/input</value>
      <webElementGuid>5802a0a5-7463-4bf8-a331-05d897507b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Postal code' and @name = 'data.postalCode' and @type = 'text' and @id = 'gigya-textbox-99294980864804060' and @placeholder = 'Insert postal code *']</value>
      <webElementGuid>547d3625-99af-4343-9c18-36aea6ddff28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
