<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Your Postal Code will be used to prov_53b101</name>
   <tag></tag>
   <elementGuidId>5816eb64-3da2-43fc-a1c6-d34dbbc7f4da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-subscribe-with-email-form > div.gigya-layout-row > div.gigya-layout-row > div.gigya-composite-control.gigya-composite-control-checkbox > div.gigya-checkbox-container > label.gigya-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[6]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Yes! I’d like to subscribe to marketing and promotional electronic communication&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>73fd3747-5613-44d7-9001-4023aecdd36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-label</value>
      <webElementGuid>d3a33b5a-8f1a-4841-ba4b-2ca1b1c0b397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-binding</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>da2073fa-910c-4a95-9fb5-57a790f7a934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_23_1757078244001</value>
      <webElementGuid>c102f716-6025-4864-bd81-c03e2b921c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2d337456-12d8-4c63-bd87-37aaa35d6d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>fa953ddf-8923-42d8-9b7a-4577d53e548b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>gigya-checkbox-36710405232980536</value>
      <webElementGuid>3a17fbf8-a122-4bce-9f7a-545b9341be9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes! I’d like to subscribe to marketing and promotional electronic communications†. You can opt out at any time.*</value>
      <webElementGuid>d2238722-443a-4008-8d45-dfabdbb5938b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-subscribe-with-email-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-checkbox&quot;]/div[@class=&quot;gigya-checkbox-container&quot;]/label[@class=&quot;gigya-label&quot;]</value>
      <webElementGuid>62a0021a-b07a-4967-a277-42fdeff65177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[6]/div/div/label</value>
      <webElementGuid>48bb795c-4dfe-4927-b16a-cfd2c979b6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Postal Code will be used to provide you with information that is specific to your area.'])[1]/following::label[1]</value>
      <webElementGuid>da32efd6-8bd9-4be8-9cf7-ed477ce4100e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::label[2]</value>
      <webElementGuid>f74de6b0-d63d-4980-9b96-50e1277b690c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[6]/div/div/label</value>
      <webElementGuid>0338198c-e8d1-4897-8e4e-ef3e6721ec32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Yes! I’d like to subscribe to marketing and promotional electronic communications†. You can opt out at any time.*' or . = 'Yes! I’d like to subscribe to marketing and promotional electronic communications†. You can opt out at any time.*')]</value>
      <webElementGuid>390403b8-7556-41c3-8e88-c32c3cd3c8e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
