<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label__gigya-label</name>
   <tag></tag>
   <elementGuidId>b4444c19-660c-4007-9f15-8d4d90e90dc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-subscribe-with-email-form > div.gigya-layout-row > div.gigya-layout-row > div.gigya-composite-control.gigya-composite-control-checkbox.agree-checkbox-copy > div.gigya-checkbox-container > label.gigya-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[7]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;By clicking, you agree to Terms of Use and Privacy Policy*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9b47b777-749f-440c-8c2e-93f11e8dd83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-label</value>
      <webElementGuid>4d6cb218-d9c4-496d-ab2d-3b7863c94c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-binding</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ef647240-434b-45e9-b0b5-b270bfe467d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_24_1757078244001</value>
      <webElementGuid>80ac0aeb-9296-4a51-974c-2ee6e29e99f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>225b9d77-a445-4fa0-82f0-cbcf23a28ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>511b979a-a1b9-450f-a45d-17ba0d3524e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>gigya-checkbox-74705580798586320</value>
      <webElementGuid>06d1a7da-8fec-4a3b-b9f2-13758e1e9aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>By clicking, you agree to  Terms of Use and Privacy Policy*</value>
      <webElementGuid>2cf94982-6a46-4a67-ac8e-15dbba386b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-subscribe-with-email-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-checkbox agree-checkbox-copy&quot;]/div[@class=&quot;gigya-checkbox-container&quot;]/label[@class=&quot;gigya-label&quot;]</value>
      <webElementGuid>37463fd0-89e5-4bcc-92dd-4335c4ccfc17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[7]/div/div/label</value>
      <webElementGuid>444460a9-976f-4ce8-b6c1-9e3a6fcf2feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='†'])[1]/following::label[2]</value>
      <webElementGuid>6cde4563-6e14-4ffc-9a3d-3eef45ddf74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Postal Code will be used to provide you with information that is specific to your area.'])[1]/following::label[3]</value>
      <webElementGuid>0e3d2592-1c94-47a7-bb9f-ec2b97819717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[7]/div/div/label</value>
      <webElementGuid>23dcbbc5-3427-4062-aba9-161c722bdbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'By clicking, you agree to  Terms of Use and Privacy Policy*' or . = 'By clicking, you agree to  Terms of Use and Privacy Policy*')]</value>
      <webElementGuid>bf4ba0a0-b67b-4f1f-81fe-29f00247cd3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
