<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__gigya-label-text</name>
   <tag></tag>
   <elementGuidId>13d2e2eb-7d06-4e6f-9aa7-ba7ccd823352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-subscribe-with-email-form > div.gigya-layout-row > div.gigya-layout-row.with-two-inputs > div.gigya-layout-cell > div.gigya-composite-control.gigya-composite-control-textbox.custom-input-left > label.gigya-label > span.gigya-label-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[3]/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;First name*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f9e4890-b47f-4dd8-a19e-64a27ff852d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-label-text</value>
      <webElementGuid>c0de2af3-800c-4315-bfb9-294ed321817e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translation-key</name>
      <type>Main</type>
      <value>TEXTBOX_89954935335929250_LABEL</value>
      <webElementGuid>cad655ae-9164-406a-8b57-a362968586ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_12_1757069345094</value>
      <webElementGuid>02af9c23-c651-4d3f-a6e7-1775a4691537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>72c69413-ba21-4a79-9dab-872beddff578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance,template</value>
      <webElementGuid>c3373f6c-fab0-4d0f-8410-7bd2c358c25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First name*</value>
      <webElementGuid>3f8ba391-f1e8-4c64-b423-39a3192348d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-subscribe-with-email-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-layout-row with-two-inputs&quot;]/div[@class=&quot;gigya-layout-cell&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-textbox custom-input-left&quot;]/label[@class=&quot;gigya-label&quot;]/span[@class=&quot;gigya-label-text&quot;]</value>
      <webElementGuid>9efa32f6-efca-48f0-aa12-b187238f99d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[3]/div/div/label/span</value>
      <webElementGuid>6f19649a-35cc-4235-82de-8afeeb0b0ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[2]</value>
      <webElementGuid>80e552be-80f4-4494-bbdc-49a1d17cfc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='First name']/parent::*</value>
      <webElementGuid>24892439-1197-465f-83a7-48d6732646c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[3]/div/div/label/span</value>
      <webElementGuid>5eb7d519-f976-4cf5-8e2f-e4b4a89aa731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'First name*' or . = 'First name*')]</value>
      <webElementGuid>f46a1322-58e5-47fd-a73a-18115112117a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
