<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__gigya-error-msg-gigya-subscribe-with-_10c5a3</name>
   <tag></tag>
   <elementGuidId>c201f940-fe2c-4ca8-b3bc-2264465718be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='gigya-error-msg-gigya-subscribe-with-email-form-profile.email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;You have already subscribed using this email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>def956dc-119e-40dd-8bc1-920f1c43372b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-error-msg gigya-error-code-400009 gigya-error-type-custom gigya-error-msg-active</value>
      <webElementGuid>24421c56-ff6e-4aca-8732-42db444b5336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bound-to</name>
      <type>Main</type>
      <value>profile.email</value>
      <webElementGuid>0567c273-6b63-405e-a9de-253fe556660e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_1_1757078243997</value>
      <webElementGuid>27351b86-c180-4f59-a772-117b31af8573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>271ac38f-f56f-455e-a114-371bb1f8fdad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance</value>
      <webElementGuid>d0c5e8ee-adf7-4f2b-b8d9-8b75c9155886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gigya-error-msg-gigya-subscribe-with-email-form-profile.email</value>
      <webElementGuid>38454cc2-bcb3-445f-b17f-7515e3b88c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You have already subscribed using this email</value>
      <webElementGuid>af34a92a-e458-457d-811b-d738833fca51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-error-msg-gigya-subscribe-with-email-form-profile.email&quot;)</value>
      <webElementGuid>5e4117c5-5691-4775-9149-febeab67a9d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='gigya-error-msg-gigya-subscribe-with-email-form-profile.email']</value>
      <webElementGuid>e4a96efb-b273-40f5-815a-372aef636e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[2]/div/span</value>
      <webElementGuid>d31e5cd8-db0c-47ed-b9a4-c96aba5204f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[1]</value>
      <webElementGuid>629a566a-15f6-4916-bd87-d06ddb43c7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::span[1]</value>
      <webElementGuid>42c5f98d-d0bd-48ac-9f90-1c339200086d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You have already subscribed using this email']/parent::*</value>
      <webElementGuid>b55e8335-ab1b-496c-ba0d-30a677b799f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[2]/div/span</value>
      <webElementGuid>ae7a455d-670b-47c4-834b-697a14431c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'gigya-error-msg-gigya-subscribe-with-email-form-profile.email' and (text() = 'You have already subscribed using this email' or . = 'You have already subscribed using this email')]</value>
      <webElementGuid>6ee7e090-d627-4e07-8545-535dba6b7f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
