<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sign up for emails_gigya-label-text</name>
   <tag></tag>
   <elementGuidId>3ca0e498-1d45-4dca-a888-3e393f396440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gigya-subscribe-with-email-form > div.gigya-layout-row > div.gigya-layout-row > div.gigya-composite-control.gigya-composite-control-textbox > label.gigya-label > span.gigya-label-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@for='gigya-textbox-email']//span[@class='gigya-label-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Email*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>638be95d-110d-4881-8f95-c557c6f056c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gigya-label-text</value>
      <webElementGuid>4e00685c-e442-4e11-954b-2cd989eb00ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translation-key</name>
      <type>Main</type>
      <value>TEXTBOX_50226806715763440_LABEL</value>
      <webElementGuid>87fb13e4-b363-4965-9276-cc981d423d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id</name>
      <type>Main</type>
      <value>__gig_template_element_11_1757069345094</value>
      <webElementGuid>702e3967-e8e4-4eb5-88c1-f57f66036645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-element-id-publish</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>59f67ca2-f0c1-4738-85aa-3e4eed9c17e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-screenset-roles</name>
      <type>Main</type>
      <value>instance,template</value>
      <webElementGuid>c0916532-4c92-4ece-9a35-f3464d8d8883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email*</value>
      <webElementGuid>dde7bdd1-71bf-4304-8d83-1a33cb79a39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gigya-subscribe-with-email-form&quot;)/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-layout-row&quot;]/div[@class=&quot;gigya-composite-control gigya-composite-control-textbox&quot;]/label[@class=&quot;gigya-label&quot;]/span[@class=&quot;gigya-label-text&quot;]</value>
      <webElementGuid>e8a06fd4-4110-4af7-aee2-096ba27dd280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='gigya-subscribe-with-email-form']/div[2]/div[2]/div/label/span</value>
      <webElementGuid>16b540f6-cf60-45fd-b3b6-72f087eaa264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up for emails'])[1]/following::span[1]</value>
      <webElementGuid>a8f86f35-9ab6-4d41-a91d-0d446c602d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscription'])[1]/following::span[1]</value>
      <webElementGuid>3f9cf064-cfe1-49d0-afc5-003059832c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email']/parent::*</value>
      <webElementGuid>16e4a559-0656-4719-adf4-93c21aedf3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[2]/div/label/span</value>
      <webElementGuid>58af3b62-929d-4c74-9d00-711ce27ce51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Email*' or . = 'Email*')]</value>
      <webElementGuid>f5e0d0b2-afcb-4382-bba4-698f5254c34f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
