<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accordion Section_item-Allergens-header</name>
   <tag></tag>
   <elementGuidId>248088bb-e2af-477d-85f1-946ed5bd3a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='item-Allergens-header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item-Allergens-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Allergens &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3066bb9-c2e9-4044-916a-cd83737fcede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>69398c34-1837-4366-bb1b-74917cd29a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item-Allergens-header</value>
      <webElementGuid>d43326fa-9933-4a94-aa26-f66e2a430c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>item-Allergens-panel</value>
      <webElementGuid>b362a333-43df-4dce-8732-01cf6e3cd97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>769ce3b5-c71a-4371-868d-7afd59f15a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center w-full text-left py-3 px-4 justify-between font-bold !px-0 pt-0 pb-2 text-[16px] lg:text-[14px] group [&amp;_.demo-icon]:w-6 [&amp;_.demo-icon]:h-6 [&amp;_.demo-icon]:flex [&amp;_.demo-icon]:items-center [&amp;_.demo-icon]:justify-center</value>
      <webElementGuid>73be4110-749a-4725-9af8-9d358df4941f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allergens</value>
      <webElementGuid>28df6ba4-466d-410e-8a72-a742887c24fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-Allergens-header&quot;)</value>
      <webElementGuid>52573757-c275-4ec0-b3dd-35d5c860cda9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='item-Allergens-header']</value>
      <webElementGuid>1ade1585-84e9-4d63-ad50-18519cac6a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='start-of-content']/div/div[2]/div/aside/div/div[3]/div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>14bbe423-2cc5-442f-be37-946d91c4a437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accordion Section'])[2]/following::button[1]</value>
      <webElementGuid>45477a49-f4f3-416e-a1bb-1a5a68ceab64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compliments'])[1]/following::button[1]</value>
      <webElementGuid>48541310-713a-40b9-a5e1-170d98420bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Egg-free'])[1]/preceding::button[1]</value>
      <webElementGuid>5ed58120-9137-4ea9-8594-f89edad344eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/button</value>
      <webElementGuid>f2cb3cc4-6b00-4cf1-9323-74513140cb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'item-Allergens-header' and (text() = 'Allergens' or . = 'Allergens')]</value>
      <webElementGuid>1dd01a50-6bb1-4a6f-9746-4bc1401ad445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
