<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Egg-free_checkboxAllergens-2</name>
   <tag></tag>
   <elementGuidId>6647ace8-026c-4f0a-87f4-173cd0cdd167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkboxAllergens-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkboxAllergens-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Gluten-free&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02709788-21a1-4d28-820f-bd5a1b2f72a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer h-[18px] w-[18px] border-none appearance-none relative before:content-[''] before:absolute before:top-0 before:left-0 before:border-solid before:rounded-[2px] before:border-2 before:border-brandBlack before:w-full before:h-full checked:before:bg-neutral-900 checked:after:content-[''] checked:after:w-[10px] checked:after:bg-brandBlack after:h-[5px] after:top-[6px] after:text-sm after:absolute after:-left-[1px] after:translate-x-1/2 after:text-brandWhite checked:after:border-l-2 after:border-l-brandWhite checked:after:border-b-2 after:border-b-brandWhite after:transform after:rotate-[-45deg] m-[15px] min-w-[18px] min-h-[18px]</value>
      <webElementGuid>7beb4680-b53e-4574-9c44-684ef847d370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkboxAllergens-2</value>
      <webElementGuid>f0811ac5-7132-4f73-9865-170e3851f349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>78ec996c-d1ac-4606-a65a-b6ab920e56eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a76d89f4-ca2a-48af-8f90-55a2fa0311b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkboxAllergens-2&quot;)</value>
      <webElementGuid>cec1b01f-6bdb-4038-b196-3f55b37cb4e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkboxAllergens-2']</value>
      <webElementGuid>e16d4902-a9ec-426e-8aff-adc358278912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item-Allergens-panel']/div/div[2]/input</value>
      <webElementGuid>d82e34ff-109a-4868-91d6-d6340167d70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>822a355d-ca7b-4447-9aab-efabd15d6840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkboxAllergens-2' and @type = 'checkbox']</value>
      <webElementGuid>9a027534-6cc1-43c9-96dd-230b001a107f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
