<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Allergens_text-14px peer-disabledcurs_ca0999</name>
   <tag></tag>
   <elementGuidId>d706de0c-d0a9-4f8b-b54e-c814d67d9d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='item-Allergens-panel']/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Egg-free&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>be66ef2e-f148-4b64-ae28-918bda8f33ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkboxAllergens-1</value>
      <webElementGuid>9f8b2809-fe3e-488b-9e5f-ade2c9986697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[14px] peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer</value>
      <webElementGuid>d2d90e58-74e5-4bb9-a9c8-b83cdf6349d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Egg-free</value>
      <webElementGuid>feb04bc9-369e-420c-81e1-e2603f69a5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-Allergens-panel&quot;)/div[@class=&quot;p-4&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/label[@class=&quot;text-[14px] peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer&quot;]</value>
      <webElementGuid>b848fed3-46e4-47b6-b4cc-eb922ef7f628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='item-Allergens-panel']/div/div/label</value>
      <webElementGuid>5495eab7-4f67-4f72-9d99-9ab9b14ea4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allergens'])[1]/following::label[1]</value>
      <webElementGuid>a1490d46-a399-4422-a031-8c6289cbe570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accordion Section'])[2]/following::label[1]</value>
      <webElementGuid>a9d8826a-376b-4b1e-aacc-8408e871d15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gluten-free'])[1]/preceding::label[1]</value>
      <webElementGuid>92c10a82-bf1c-4f7e-8034-9819095a80fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kosher'])[1]/preceding::label[2]</value>
      <webElementGuid>ecb2656d-3a23-4678-baba-793b0d525058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Egg-free']/parent::*</value>
      <webElementGuid>c3d3b215-4b5e-4bcc-af05-a3ccb87f29e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/label</value>
      <webElementGuid>149466c4-f0da-42c2-b244-0346559defe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Egg-free' or . = 'Egg-free')]</value>
      <webElementGuid>c193cd5b-7c2f-410b-bf76-faa9ea78320a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
