<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Promise Gluten-Free Sandwich Rolls Han_option-3</name>
   <tag></tag>
   <elementGuidId>37e236b4-b18f-42b9-90dd-d651ca1424fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='option-3'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;20 / Page&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>92ff6a0b-2243-4950-8cf0-cffab2cf765f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d8b8b60f-5e37-443f-b55c-572549a4d720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-3</value>
      <webElementGuid>97c9b735-cf4f-4840-8075-670bf6e1b177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e58bbac4-9898-420c-8f9b-e943b310685c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b1cba8b0-e735-49f0-999d-da640cf220f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5c534481-99f1-47ed-9c3b-69c1338a77d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab flex gap-3 items-center text-base text-brandBlack py-2 px-4 hover:bg-grey300 hover:text-brandBlack cursor-pointer 
                            </value>
      <webElementGuid>42e76d6b-ce2e-4690-bbf1-71d262ed5304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20 / Page</value>
      <webElementGuid>1ef2b304-3f0a-489d-985e-0edfbcc40487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-of-content&quot;)/div[1]/div[@class=&quot;mx-auto px-6 2md:px-12 max-w-[1536px] main-wrapper lg:mt-6&quot;]/div[@class=&quot;flex lg:gap-[24px]&quot;]/main[@class=&quot;pb-8 md:pb-6 lg:pb-12 w-full lg:w-[calc(100%-250px)] xl:w-[calc(100%-220px)]&quot;]/div[@class=&quot;flex flex-col lg:flex-row gap-4 lg:gap-6 justify-center items-center w-[100%] mt-6&quot;]/div[@class=&quot;relative tab relative  [&amp;_button]:rounded-[4px] [&amp;_button]:text-brandBlack [&amp;_span:last-child]:right-[14px] [&amp;_button]:py-[4.5px] [&amp;_button]:pl-[8px] [&amp;_button]:pr-[36px] [&amp;_li]:py-[4.5px] [&amp;_li]:text-[14px]&quot;]/ul[@class=&quot;shadow-[0_4px_30px_0px_rgba(0,0,0,0.07)] rounded-[5px] z-10 bg-brandWhite py-[0px] absolute left-0 top-full w-full overflow-hidden  block&quot;]/li[@id=&quot;option-3&quot;]</value>
      <webElementGuid>d0d796af-8d7c-4a55-a882-337df98e3925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@id='option-3'])[2]</value>
      <webElementGuid>1569ee29-bf58-4d0d-9dbe-43b56da83a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='start-of-content']/div/div[2]/div/main/div[2]/div[2]/ul/li[4]</value>
      <webElementGuid>0bfcd27d-bcd5-4394-8b20-184b4d9b0e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promise Gluten-Free Sandwich Rolls Han...'])[1]/following::li[5]</value>
      <webElementGuid>fdd2054e-e2a2-4c2d-9ff3-19c4a7238bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$9.99'])[1]/following::li[5]</value>
      <webElementGuid>1fbca6b1-bfc9-4160-a001-d87266ec53a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product availability may vary. See in-store for accurate product availability.'])[1]/preceding::li[3]</value>
      <webElementGuid>dd8344a4-c41b-46d9-b8d2-c2f99f31dc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Service'])[1]/preceding::li[3]</value>
      <webElementGuid>216800d6-bc71-4007-9fbb-4a9185f24e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20 / Page']/parent::*</value>
      <webElementGuid>d6b073ed-bd89-4176-914d-a6a77f08457e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]</value>
      <webElementGuid>ce2ec5bc-fca7-41a8-8628-4a3f92895e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'option-3' and (text() = '20 / Page' or . = '20 / Page')]</value>
      <webElementGuid>be6235b9-e1b7-400a-90c4-0a71fb4b0f11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
