<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search Recipes_text-14px icon icon-close</name>
   <tag></tag>
   <elementGuidId>86daf03d-3b4f-4bcc-a63d-7be87188fbe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bed12666-36d5-48c0-919e-3297bd17f54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>39d3932a-04b2-4548-9662-91f7afa9be03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[14px] icon icon-close</value>
      <webElementGuid>8fa605e1-695a-4f46-8743-f0c6d64feba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_00123d __variable_51684b __className_51684b __variable_4ddf73 __variable_7b4501 site-sobeys&quot;]/div[3]/div[1]/header[@class=&quot;sticky top-0 z-20 w-full left-0&quot;]/div[@class=&quot;bg-brandSecondary py-3&quot;]/div[@class=&quot;mx-auto px-6 2md:px-12 max-w-[1536px]&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12&quot;]/div[@class=&quot;relative flex w-full max-w-none items-center justify-between lg:justify-normal&quot;]/div[@class=&quot;desktop-search block md:hidden lg:block z-10 flex-1  !md:mx-0 !2lg:ml-6 !lg:mx-0 mr-3 3xl:mr-0 lg:!ml-3 ml-auto max-w-[calc(100%-90px)]&quot;]/div[@class=&quot;w-full 5xl:max-w-[708px] md:max-w-[calc(100%-0px)] mx-auto min-w-auto 2lg:min-w-auto lg:mx-0 lg:pr-6  2lg:pr-12 5xl:pr-0&quot;]/div[@class=&quot;autocomplete-search relative [&amp;_input]:h-[40px] [&amp;_input]:!border-1 [&amp;_input]:xl:text-base [&amp;_input]:text-grey900 !static [&amp;_input]:w-full [&amp;_input]:pl-[16px] [&amp;_input]:pr-[40px] [&amp;_.close-button]:right-[0] [&amp;_.dropDown]:6xl:w-[1440px] [&amp;_.dropDown]:6xl:max-w-[1440px] [&amp;_.dropDown]:border-grey350 [&amp;_.dropDown]:border [&amp;_.dropDown]:w-full [&amp;_.dropDown]:!left-0 [&amp;_.dropDown]:!right-0 [&amp;_.dropDown]:!mx-auto [&amp;_.dropDown]:rounded-[4px] [&amp;_.dropDown]:max-w-[100%] [&amp;_.dropDown]:4xs:max-w-[calc(100%-48px)] [&amp;_.dropDown]:md:max-w-[calc(100%-49px)] [&amp;_.dropDown]:2md:max-w-[calc(100%-100px)] [&amp;_.dropDown]:lg:max-w-[calc(100%-0px)] [&amp;_.dropDown]:m-0 [&amp;_.dropDown]:min-[320px]:max-w-[calc(100%-48px)] [&amp;_.dropDown]:overflow-y-auto [&amp;_.dropDown]:md:overflow-y-hidden [&amp;_.dropDown-content]:h-full [&amp;_.dropDown].px-3.mx-auto.max-w-full:h-full [&amp;_.dropDown-body>div]:h-full [&amp;_.dropDown-body>div>.row]:h-full [&amp;_.dropDown-body]:h-full [&amp;_.cursor-pointer]:z-[9999999] [&amp;_.cursor-pointer~div]:z-[999] [&amp;_.dropDown]:5xl:h-auto [&amp;_.dropDown]:max-h-[calc(100vh-190px)] [&amp;_.dropDown]:md:max-h-[calc(100vh-190px)] [&amp;_.dropDown]:4xs:h-auto [&amp;_.inputWrapper]:bg-[white] [&amp;_.inputWrapper]:z-[999] [&amp;_input]:bg-transparent [&amp;_input]:z-[99999] [&amp;_.inputWrapper]:after:rounded-[5px] [&amp;_.inputWrapper]:after:content-[''] [&amp;_.inputWrapper]:after:absolute [&amp;_.inputWrapper]:after:top-0 [&amp;_.inputWrapper]:after:bg-brandWhite [&amp;_.inputWrapper]:after:z-[999] [&amp;_.inputWrapper]:border [&amp;_.inputWrapper]:border-grey350 [&amp;_.inputWrapper]:after:overflow-hidden [&amp;_.inputWrapper]:rounded-[5px] [&amp;_.inputWrapper]:after:w-full [&amp;_.inputWrapper]:after:h-full [&amp;_.inputWrapper]:overflow-hidden [&amp;_.inputWrapper>div]:leading-[20px] [&amp;_.inputWrapper]:overflow:!hidden [&amp;_.inputWrapper]:before:content-[''] [&amp;_.inputWrapper]:before:absolute [&amp;_.inputWrapper]:before:left-0 [&amp;_.inputWrapper]:before:h-full [&amp;_.inputWrapper]:before:w-4 [&amp;_.inputWrapper]:before:top-0 [&amp;_.inputWrapper]:before:bg-[#fff] [&amp;_.inputWrapper]:before:z-[99999] [&amp;_.open-button>button]:h-[40px] [&amp;_.open-button]:p-0 [&amp;_.open-button>button]:w-[40px] [&amp;_input]:placeholder:opacity-[0.6] [&amp;_input]:placeholder:text-brandBlack&quot;]/div[@class=&quot;relative inputWrapper&quot;]/form[1]/div[@class=&quot;tab absolute min-w-[40px] top-0 px-[8px] right-[0px] z-[9999] text-center &#xd;
                h-[100%] cursor-pointer flex items-center justify-center&quot;]/div[@class=&quot;text-[14px] icon icon-close&quot;]</value>
      <webElementGuid>a1d4ecd3-5fd8-4414-9cbc-3154e1fef096</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>ed81ecc6-a656-44f8-a018-a7f5b77377f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
