<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_View All_mobImageCat</name>
   <tag></tag>
   <elementGuidId>b84697c3-fe8f-4db8-953c-2758bbd9b504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Categories']/div[2]/div/div/section/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mobImageCat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Bread &amp; Bakery&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>645dec3d-9c8c-46da-8aa9-fad1d8822e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bread &amp; Bakery</value>
      <webElementGuid>45048c94-9438-42e1-91ce-aabbfa82bbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ad2e8ddd-30a0-46c0-8809-d5acf7dc1128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>96</value>
      <webElementGuid>8f8c11f8-7163-4849-b158-cf8de39bfd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>96</value>
      <webElementGuid>7b5b0b64-dc14-4a80-9c40-d4b79761f2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>068adb0b-c17c-488a-bb45-a21f4eba424a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f20ca2c1-5535-4dd0-b7f4-447db441e558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mobImageCat</value>
      <webElementGuid>b0d2aa17-6849-44b9-80b5-10438c518462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Faem-qa.sobeys.com%2Fadobe%2Fdynamicmedia%2Fdeliver%2Fdm-aid--14606949-5de1-4769-b684-fbcc47fbf375%2Fbread-bakery.svg%3Fpreferwebp%3Dtrue&amp;w=96&amp;q=75 1x, /_next/image?url=https%3A%2F%2Faem-qa.sobeys.com%2Fadobe%2Fdynamicmedia%2Fdeliver%2Fdm-aid--14606949-5de1-4769-b684-fbcc47fbf375%2Fbread-bakery.svg%3Fpreferwebp%3Dtrue&amp;w=256&amp;q=75 2x</value>
      <webElementGuid>032dc0e6-b174-422d-9556-047778eaba80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Faem-qa.sobeys.com%2Fadobe%2Fdynamicmedia%2Fdeliver%2Fdm-aid--14606949-5de1-4769-b684-fbcc47fbf375%2Fbread-bakery.svg%3Fpreferwebp%3Dtrue&amp;w=256&amp;q=75</value>
      <webElementGuid>fa5adb2f-b816-483a-943e-dfec5d1d4ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-of-content&quot;)/div[@id=&quot;Categories&quot;]/div[@class=&quot;mx-auto px-6 2md:px-12 max-w-[1536px] !pl-6 !pr-0 2md:!pl-12 lg:!px-12 HomeSliderRight&quot;]/div[@class=&quot;mb-[0px]&quot;]/div[@class=&quot;categorySliderEmbla&quot;]/section[@class=&quot;embla__wrapper mx-auto w-full max-w-full embla_CategorySlider&quot;]/div[@class=&quot;embla__row&quot;]/div[@class=&quot;embla__viewport pt-[2px] !pb-2 relative&quot;]/div[@class=&quot;embla__container&quot;]/div[@class=&quot;embla__slide items-stretch tab embla__slide--active&quot;]/div[@class=&quot;mb-[8px] lg:mb-[10px] mt-[4px]&quot;]/div[@class=&quot;flex flex-col items-center justify-center gap-[8px] cursor-pointer&quot;]/img[@class=&quot;mobImageCat&quot;]</value>
      <webElementGuid>1a2e6570-b6b1-4103-b489-75a6dec90d29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Categories']/div[2]/div/div/section/div/div/div/div/div/div/img</value>
      <webElementGuid>10b7c5cc-aa4f-47e7-a39b-7ae15b06e389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bread &amp; Bakery']</value>
      <webElementGuid>0a961067-1d7f-488d-b2e6-c66e0924f213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/div/img</value>
      <webElementGuid>31e47dfe-76c3-4594-997f-c221dcfdc83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Bread &amp; Bakery' and @src = '/_next/image?url=https%3A%2F%2Faem-qa.sobeys.com%2Fadobe%2Fdynamicmedia%2Fdeliver%2Fdm-aid--14606949-5de1-4769-b684-fbcc47fbf375%2Fbread-bakery.svg%3Fpreferwebp%3Dtrue&amp;w=256&amp;q=75']</value>
      <webElementGuid>90a19929-78cd-453f-8e81-d8e6f5df0173</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
