<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name your shopping list_createListInput</name>
   <tag></tag>
   <elementGuidId>efb7d628-ae1d-48a9-96a5-8d9e906e0203</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createListInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#createListInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g Sunday BBQ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04f7de31-dc8c-4cb5-a4c0-396b754f8e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-solid border-[1px] p-4 w-full h-14 border-grey350 rounded py-1 placeholder:text-brandBlack focus-visible:outline-brandBlack</value>
      <webElementGuid>8b8316e1-973a-453a-8fac-cf20b65ef265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createListInput</value>
      <webElementGuid>62d11ad3-691c-4320-89cc-c2d857247857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g Sunday BBQ</value>
      <webElementGuid>68d02d52-45ee-4f13-ac9f-8e3d947e22c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>4d31cfe9-1453-490f-886a-c20b5bf14ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7fe169e0-d48c-4a49-a23c-d772b9ff79ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1efb1fc2-98f1-4c20-ba55-44fb2fdc5584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>createListInput</value>
      <webElementGuid>4fc5c366-9fae-4a07-aab7-4d8084bee702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createListInput&quot;)</value>
      <webElementGuid>f66cd09f-9593-43ac-aab9-b8c614ca7b48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createListInput']</value>
      <webElementGuid>b3dd24d3-9c5e-4fee-9ebe-4619afc07472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>e4426adc-a6cc-49ca-92e1-4d03666b0113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'createListInput' and @placeholder = 'e.g Sunday BBQ' and @type = 'text' and @name = 'createListInput']</value>
      <webElementGuid>067387f6-21dd-4126-b645-945c5bb30979</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
