<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Alphabetical Z-A_option-2</name>
   <tag></tag>
   <elementGuidId>a4607a37-2753-4d60-be28-351c9a4eb33d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='option-1'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Newest Date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ae93db55-4ecb-4339-b7f3-0fc79246e227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c7283ff3-bf75-47a1-ace2-35bd2b41a1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-2</value>
      <webElementGuid>6a689f5f-eeaf-42a0-af89-e1df150bafe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34e46a23-9109-42d7-84b6-d13f08181ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b68430e5-30d1-465c-9362-8eff8faf7112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>dxp_recipes_en_publish_desc</value>
      <webElementGuid>0ba2f053-f96e-4f26-84f3-04d37531cde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab flex gap-3 items-center text-base text-brandBlack py-2 px-4 hover:bg-grey300 hover:text-brandBlack cursor-pointer 
                            </value>
      <webElementGuid>0dda0fec-0212-4d1f-8f2f-ed836c7ed6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Newest Date</value>
      <webElementGuid>5c3fcfb8-65d5-4491-a289-59a2c0ac3e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-of-content&quot;)/div[@class=&quot;h-full min-h-[400px] visible&quot;]/div[2]/div[@class=&quot;mx-auto 2md:px-12 max-w-[1536px] w-full px-0 lg:px-12&quot;]/div[@class=&quot;row  !mx-0&quot;]/div[@class=&quot;col-12 !px-0&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;aria-selected:block hidden [&amp;_.main-wrapper]:!px-0 [&amp;_.main-wrapper] [&amp;_.main-wrapper_.filter-mobile]:!bg-grey100 [&amp;_.main-wrapper_.filter-mobile]:lg:before:content-none [&amp;_.main-wrapper_.filter-mobile]:lg:before:content-none [&amp;_.main-wrapper_.filter-mobile]:before:content-[''] [&amp;_.main-wrapper_.filter-mobile]:before:absolute [&amp;_.main-wrapper_.filter-mobile]:before:left-[-64px] [&amp;_.main-wrapper_.filter-mobile]:before:top-0 [&amp;_.main-wrapper_.filter-mobile]:before:w-[24%] [&amp;_.main-wrapper_.filter-mobile]:before:h-full [&amp;_.main-wrapper_.filter-mobile]:relative [&amp;_.main-wrapper_.filter-mobile]:before:bg-grey100 [&amp;_.main-wrapper_.filter-mobile]:after:content-[''] [&amp;_.main-wrapper_.filter-mobile]:after:absolute [&amp;_.main-wrapper_.filter-mobile]:2md:after:right-[-48px] [&amp;_.main-wrapper_.filter-mobile]:after:right-0 [&amp;_.main-wrapper_.productMain_.filter-mobile]:after:right-[-24px] [&amp;_.main-wrapper_.filter-mobile]:after:top-0 [&amp;_.main-wrapper_.filter-mobile]:2md:after:w-[calc(100%-48px)] [&amp;_.main-wrapper_.filter-mobile]:after:w-[calc(100%-24px)] [&amp;_.main-wrapper_.productMain_.filter-mobile]:2md:after:right-[-48px] [&amp;_.main-wrapper_.productMain_.filter-mobile]:px-0 [&amp;_.main-wrapper_.productMain_.filter-mobile>div]:md:w-auto [&amp;_.main-wrapper_.filter-mobile]:after:h-full [&amp;_.main-wrapper_.filter-mobile]:relative [&amp;_.main-wrapper_.filter-mobile]:after:bg-grey100 [&amp;_.main-wrapper_.filter-mobile]:bg-grey350[&amp;_.main-wrapper_.filter-mobile]:2md:bg-brandWhite [&amp;_.main-wrapper_.filter-mobile]:py-[16px] [&amp;_.main-wrapper_.filter-mobile]:px-6 [&amp;_.main-wrapper_.filter-mobile]:2md:px-0 [&amp;_.main-wrapper_.recipeMain]:px-6 [&amp;_.main-wrapper_.recipeMain]:2md:px-0 [&amp;_.main-wrapper_.row]:!m-0 [&amp;_.main-wrapper_.col-12]:!px-0 [&amp;_.productWrapper]:!px-0 [&amp;_.main-wrapper_.productMain]:pt-0 [&amp;_.main-wrapper_.productMain]:2md:px-0 [&amp;_.main-wrapper_.productMain]:px-6 [&amp;_.main-wrapper_.articleMain]:px-6 [&amp;_.main-wrapper_.articleMain]:2md:px-0  [&amp;_.main-wrapper_.grid-outer]:pt-0 [&amp;_.main-wrapper_.products-p]:px-6 [&amp;_.main-wrapper_.products-p]:2md:px-0 [&amp;_.main-wrapper_.products-p]:m-0&quot;]/div[1]/div[@class=&quot;mx-auto px-6 2md:px-12 max-w-[1536px] main-wrapper lg:mt-6&quot;]/div[@class=&quot;flex lg:gap-[24px]&quot;]/aside[@class=&quot;lg:w-[250px] xl:w-[220px] mb-[38px] sideBar&quot;]/div[@class=&quot;flex flex-col gap-4 lg:w-[250px] xl:w-[220px]&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@id=&quot;recipe_tour_1&quot;]/div[@class=&quot;relative [&amp;>button]:text-grey900 [&amp;>button]:rounded-[4px] [&amp;>button]:pl-4 [&amp;>button]:h-[56px] [&amp;>button]:py-3 [&amp;>button]:pr-12 [&amp;>button>span]:text-base [&amp;>ul]:!shadow-[0_4px_30px_0px_rgba(0,0,0,0.2)]&quot;]/ul[@class=&quot;shadow-[0_4px_30px_0px_rgba(0,0,0,0.07)] rounded-[5px] z-10 bg-brandWhite py-[0px] absolute left-0 top-full w-full overflow-hidden  block&quot;]/li[@id=&quot;option-2&quot;]</value>
      <webElementGuid>0413be64-74f2-4104-bce9-e2feccf54df1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@id='option-2'])[3]</value>
      <webElementGuid>70388fb0-afac-4ed7-aa00-de4539cc8c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='recipe_tour_1']/div/ul/li[3])[2]</value>
      <webElementGuid>77ad5d16-f5ab-49fe-8cce-7f4b8a0de4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alphabetical: Z-A'])[3]/following::li[1]</value>
      <webElementGuid>c2d2820e-2a99-43e2-b5e9-7f641f9ee084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alphabetical: A-Z'])[2]/following::li[2]</value>
      <webElementGuid>1eee9097-1981-4ec3-a60a-09fa805f4b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oldest Date'])[1]/preceding::li[1]</value>
      <webElementGuid>cdfe924c-8b79-4d07-bea6-ccb948696b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[4]/preceding::li[2]</value>
      <webElementGuid>f2d9e58b-c2b8-44d0-848a-71dd322db2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Newest Date']/parent::*</value>
      <webElementGuid>edd63596-73f6-4f55-9e83-f8e3c3342dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/aside/div/div/div[2]/div/ul/li[3]</value>
      <webElementGuid>5762bca3-c2cd-44b1-95cb-8ac039b84f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'option-2' and (text() = 'Newest Date' or . = 'Newest Date')]</value>
      <webElementGuid>db5e17fb-ff31-4c0f-93c6-924677097f4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
