<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Newest Date_option-4</name>
   <tag></tag>
   <elementGuidId>f3f29be2-bd9a-4165-9392-0d6843006ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id='option-4'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Oldest Date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ffe4d333-a5d1-4d36-9865-7587643f61e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>730f726b-e1af-410d-8ef6-6fc707205d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-4</value>
      <webElementGuid>64b5e47e-15e9-4e21-958e-50227e053014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb831b06-f0e4-4390-8bba-8bc939074fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>cbd26e95-9d91-4e5b-9fc9-68a7592aa9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>dxp_articles_en_publish_asc</value>
      <webElementGuid>1d0f9be7-874b-4f32-8041-80e09a7c3c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab flex gap-3 items-center text-base text-brandBlack py-2 px-4 hover:bg-grey300 hover:text-brandBlack cursor-pointer 
                            </value>
      <webElementGuid>7d97dec8-d8c6-4e8c-92d1-880796fe606f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oldest Date</value>
      <webElementGuid>04bc94b4-161e-4956-955d-1ce134a3b49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-of-content&quot;)/div[@class=&quot;h-full min-h-[400px] visible&quot;]/div[2]/div[@class=&quot;mx-auto 2md:px-12 max-w-[1536px] w-full px-0 lg:px-12&quot;]/div[@class=&quot;row  !mx-0&quot;]/div[@class=&quot;col-12 !px-0&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;aria-selected:block hidden [&amp;_.main-wrapper]:!px-0 [&amp;_.main-wrapper] [&amp;_.main-wrapper_.filter-mobile]:!bg-grey100 [&amp;_.main-wrapper_.filter-mobile]:lg:before:content-none [&amp;_.main-wrapper_.filter-mobile]:lg:before:content-none [&amp;_.main-wrapper_.filter-mobile]:before:content-[''] [&amp;_.main-wrapper_.filter-mobile]:before:absolute [&amp;_.main-wrapper_.filter-mobile]:before:left-[-64px] [&amp;_.main-wrapper_.filter-mobile]:before:top-0 [&amp;_.main-wrapper_.filter-mobile]:before:w-[24%] [&amp;_.main-wrapper_.filter-mobile]:before:h-full [&amp;_.main-wrapper_.filter-mobile]:relative [&amp;_.main-wrapper_.filter-mobile]:before:bg-grey100 [&amp;_.main-wrapper_.filter-mobile]:after:content-[''] [&amp;_.main-wrapper_.filter-mobile]:after:absolute [&amp;_.main-wrapper_.filter-mobile]:2md:after:right-[-48px] [&amp;_.main-wrapper_.filter-mobile]:after:right-0 [&amp;_.main-wrapper_.productMain_.filter-mobile]:after:right-[-24px] [&amp;_.main-wrapper_.filter-mobile]:after:top-0 [&amp;_.main-wrapper_.filter-mobile]:2md:after:w-[calc(100%-48px)] [&amp;_.main-wrapper_.filter-mobile]:after:w-[calc(100%-24px)] [&amp;_.main-wrapper_.productMain_.filter-mobile]:2md:after:right-[-48px] [&amp;_.main-wrapper_.productMain_.filter-mobile]:px-0 [&amp;_.main-wrapper_.productMain_.filter-mobile>div]:md:w-auto [&amp;_.main-wrapper_.filter-mobile]:after:h-full [&amp;_.main-wrapper_.filter-mobile]:relative [&amp;_.main-wrapper_.filter-mobile]:after:bg-grey100 [&amp;_.main-wrapper_.filter-mobile]:bg-grey350[&amp;_.main-wrapper_.filter-mobile]:2md:bg-brandWhite [&amp;_.main-wrapper_.filter-mobile]:py-[16px] [&amp;_.main-wrapper_.filter-mobile]:px-6 [&amp;_.main-wrapper_.filter-mobile]:2md:px-0 [&amp;_.main-wrapper_.recipeMain]:px-6 [&amp;_.main-wrapper_.recipeMain]:2md:px-0 [&amp;_.main-wrapper_.row]:!m-0 [&amp;_.main-wrapper_.col-12]:!px-0 [&amp;_.productWrapper]:!px-0 [&amp;_.main-wrapper_.productMain]:pt-0 [&amp;_.main-wrapper_.productMain]:2md:px-0 [&amp;_.main-wrapper_.productMain]:px-6 [&amp;_.main-wrapper_.articleMain]:px-6 [&amp;_.main-wrapper_.articleMain]:2md:px-0  [&amp;_.main-wrapper_.grid-outer]:pt-0 [&amp;_.main-wrapper_.products-p]:px-6 [&amp;_.main-wrapper_.products-p]:2md:px-0 [&amp;_.main-wrapper_.products-p]:m-0&quot;]/div[1]/div[@class=&quot;mx-auto px-6 2md:px-12 max-w-[1536px] main-wrapper lg:mt-6&quot;]/div[@class=&quot;flex lg:gap-[24px]&quot;]/aside[@class=&quot;lg:w-[250px] xl:w-[220px] mb-[38px] sideBar&quot;]/div[@class=&quot;flex flex-col gap-4 lg:w-[250px] xl:w-[220px]&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@id=&quot;recipe_tour_1&quot;]/div[@class=&quot;relative [&amp;>button]:text-grey900 [&amp;>button]:rounded-[4px] [&amp;>button]:pl-4 [&amp;>button]:h-[56px] [&amp;>button]:py-3 [&amp;>button]:pr-12 [&amp;>button>span]:text-base [&amp;>ul]:!shadow-[0_4px_30px_0px_rgba(0,0,0,0.2)]&quot;]/ul[@class=&quot;shadow-[0_4px_30px_0px_rgba(0,0,0,0.07)] rounded-[5px] z-10 bg-brandWhite py-[0px] absolute left-0 top-full w-full overflow-hidden  block&quot;]/li[@id=&quot;option-4&quot;]</value>
      <webElementGuid>18e72af6-3f52-44f3-9cdd-3f91733ed88d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@id='option-4'])[5]</value>
      <webElementGuid>57c65a1c-4a65-44d3-b7af-6d8ff3271612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='recipe_tour_1']/div/ul/li[5])[3]</value>
      <webElementGuid>501e4e50-c8ea-48bc-af3b-796dec6a4a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newest Date'])[3]/following::li[1]</value>
      <webElementGuid>d1d98fd2-9d41-4da0-9c08-82e8945e4baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alphabetical: Z-A'])[3]/following::li[2]</value>
      <webElementGuid>8ab19202-0dcc-4e06-a89e-c75e8cb1ed60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accordion Section'])[11]/preceding::li[1]</value>
      <webElementGuid>2ad629e1-7f4c-46c2-8fc6-c750ef4407e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[2]/preceding::li[1]</value>
      <webElementGuid>c2807313-1c38-4463-8ded-c2b8da6e9be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/aside/div/div/div[2]/div/ul/li[5]</value>
      <webElementGuid>bb9a5361-6fc0-4a77-afc7-f8384fc40b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'option-4' and (text() = 'Oldest Date' or . = 'Oldest Date')]</value>
      <webElementGuid>9e2e96fc-88ca-4ea0-a3c9-1bbc45efe3d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
